### PR TITLE
Added byte serving capability to http server (206 range request)

### PR DESCRIPTION
**Pull request by riaan53**
Hi!

I thought this might be of use to others :)

I added http 206 range request to the http get method. This will allow for audio/video streaming and use of the video/audio seek bar.

I also added a new query parameter to be able to cache selected files in the browser, which is very useful for videos/images/audio. For example: '?cache=172800' will set 'cache-control:max-age=172800, private' in the header. This can be improved later on with more options and so on.

The '?download=false' query parameter will work now. A string compare was done as query params is return as string and not bool.

Notes:
- Im not used to coffee script so might have missed something :)
- Im receiving 'Warning: gridfs-locking-stream received duplicate end/close events for file' while streaming a lot and doing a lot of range requests.
- I modified your demo app and wanted to host it on amazon but I received 'js-bson: Failed to load c++ bson extension, using pure JS version'. The app starts but am not able to download a file successfully. I saw the ticket that you fixed and install c++ but it did not help. Ubuntu 14.04.1 LTS on amazon free tier.
- You can find the modified sample app here: https://github.com/riaan53/meteor-file-sample-app . Will do a PR if you want but first want to make some improvements to the things I did - dynamic templates and clean-up. 
- I tested it in chrome, safari and iOS iphone5 cordova. All latest versions as of now.

Let me know if you want me to make some changes if you want to accept the PR.

Regards,
Riaan

### CODE REVIEW

**Comment by riaan53** [comment]
You can also use curl to test this: 

curl  --header "Range: bytes=0-20000" http://localhost:3000/gridfs/fs/451e22bce5cf6f36941158f0e2c4c2bb -o part1
curl  --header "Range: bytes=20001-36907" http://localhost:3000/gridfs/fs/451e22bce5cf6f36941158f0e2c4c2bb -o part2
cat part1 part2 >> test1.avi

Will update/fix if I find some problems - im going to use this a lot.

**Comment by vsivsi** [comment]
@riaan53 Hi, I'm just recently back from vacation. Thanks for this question and for the other work you've done on other topics. I'll start working on these tomorrow. Thanks for your patience!

**Comment by vsivsi** [comment]
Hi Riaan, thanks for the PR! This looks like a great feature addition for file-collection. 

Can you add working unit tests to for the `Range:` and `?cache=NNNN` features you've added in the file: https://github.com/vsivsi/meteor-file-collection/blob/master/file_collection_tests.coffee

You can run the unit tests using `meteor test-packages` in the package source directory.  If you're not familiar with tiny-test, check here for an introduction:  https://www.eventedmind.com/feed/meteor-testing-packages-with-tinytest

**Comment by riaan53** [comment]
Hi @vsivsi ,

I have fixed an exception case and added the unit tests. Let me know if there are anything else.

Im just concerned about the 'Warning: gridfs-locking-stream received duplicate end/close events for file' im receiving?

**Comment by riaan53** [comment]
Just hang on before merging.

**Comment by vsivsi** [comment]
Okay, I'm going to start reviewing these changes, but I'll hold off on merging.

**Comment by vsivsi** [comment]
Also, FYI: The warning: `gridfs-locking-stream received duplicate end/close events for file _id:` is probably happening because with the new range functionality, you are no longer reading to the end of the gridFS file, which causing the gridFS driver to emit both an `end` event and a `close` event. If you read all of the way to the end, I believe it only emits a `close`.  `gridfs-locking-stream` is my npm package, and I've had issues with this in the past, and so I added checks and warnings to cover all cases. I think it's behaving properly, but I'll verify that and suppress the warning in the underlying package before publishing a new version of file-collection. 

Here are some links to the prior issues if you're interested:

https://github.com/vsivsi/meteor-file-collection/issues/24
https://github.com/vsivsi/gridfs-locking-stream/issues/1
https://github.com/aheckmann/gridfs-stream/issues/46

**Comment by riaan53** [comment]
Hi @vsivsi , Thank you I will investigate.

I need your help with something. I have found the strange behaviour I was talking about. When using findOneStream from gridfs it immediately reads the whole file/stream or range requested not depending on the output flow. 

I have changed the findOneStream with a normal file stream (the same file i uploaded, about 50mb) and I can see the difference. Even though the browser requests the full range of the movie/stream it only buffers/download a few mb at at time depending on where you are. More or less 2.3mb when you open it in chrome with default player settings for the first time. When reading the stream from fs.createReadStream 4325376 bytes are read from the stream and increases when input gets hungry. And when from findOneStream 51381683 bytes (full file). The problem with that is that data gets lost - movie only works till the end if you immediately play it (not pause for a while). I think this can cause problems even with normal file downloads on a very slow internet connection.

```
        path = Npm.require 'path'
        fs = Npm.require 'fs'

        # Read the partial request from gridfs stream
        #stream = @findOneStream(
        #  _id: req.gridFS._id
        #,
        #  range:
        #    start: start
        #    end: end
        #)

        base = process.env.PWD
        file = base+"/public/movie.mp4"
        stream = fs.createReadStream(file,
          start: start
          end: end
        )

        total = 0
        stream.on 'data', (data) ->
          total += data.length
          console.log total
``` 

Any ideas?

Regards,
Riaan

**Comment by riaan53** [comment]
I have just added a simple resume stream on output drain and pause after a data chunk is read/sent - it seams to solve the problem! Works perfectly now. I will add the necessary changes, test and commit.

**Comment by riaan53** [comment]
Sorry scratch my previous comment - I did it with the wrong stream :( It does not seem to work with gridfs streams. Maybe im doing something wrong?

**Comment by vsivsi** [comment]
Hi, my gridfs-locking-stream NPM package is just a locking wrapper around another package called [gridfs-stream](https://www.npmjs.com/package/gridfs-stream) (locking is necessary to protect gridFS files during attempted concurrent accesses see: https://jira.mongodb.org/browse/NODE-157).  

My package doesn't touch the flow-control aspects of the underlying streams created by gridfs-stream, so the problem you are describing, if confirmed, is very likely to be an issue in gridfs-stream. With that said, it's a stable package with a lot of users, and so it would be surprising for its streaming to be so blatantly broken. Although, having said that, I'm not sure that gridfs-stream implements *new-style* node 0.10 streams. They may well be the older type streams, which means that explicit `pause()` calls may be necessary. See this note if you aren't familiar with the old style steam functionality: http://nodejs.org/api/stream.html#stream_compatibility_with_older_node_versions

**Comment by vsivsi** [comment]
FYI: This may be something to try...  http://nodejs.org/api/stream.html#stream_readable_wrap_stream

**Comment by vsivsi** [comment]
The latest revision to gridfs-stream included a "fix" to a `pause()` related bug.  See: https://github.com/aheckmann/gridfs-stream/issues/46
The write-up doesn't give me great confidence that `pause()` is now working correctly however...

**Comment by riaan53** [comment]
I have prototype gridfs-stream with readable.wrap(stream) and it seams to work! Thank you node!

I will try this out tonight on file-collection and let you know the outcome. I also want to make a small change for the invalid range request - need to send the correct range back in the header.

**Comment by riaan53** [comment]
Hi @vsivsi ,

The readable.wrap(stream) unfortunately did not work :( Will debug some more tonight.

Regards,
Riaan

**Comment by vsivsi** [comment]
@riaan53   Thanks for keeping me posted.  Feel free to share more details about what is or isn't working in your testing. I may have more thoughts or insights that could be of help.

**Comment by riaan53** [comment]
Hi,

I have been doing some tests with gridfs-stream and it looks like the pause/resume functionality is not working like a "normal" node stream. This means that the pipe functionality (pipe uses pause/resume) wont be able to control the flow of the stream depending on the ability of the writestream, it just sends all the data at once - unfortunately not good for video/audio streaming :( . 

The guys over there are very nice and the give some idees and things to look at. I have also added a simple failing testcase to explain what im trying to achieve. You can see our discussion here: https://github.com/aheckmann/gridfs-stream/pull/47 .

My next steps are: 
- Looking at how the stream pause functionality works in the mongo driver for the version gridfs-stream is using (v1.4.3).
- If they do not support the pause functionality like I want in that mongo drive then will have to look into the new driver (v2.0.14)

Any thoughts are welcome please!

Thank you.

Regards,
Riaan

**Comment by riaan53** [comment]
Hi @vsivsi ,

I have committed the md5 re-calculation and the two other small fixes so this PR is now also ready.

The only thing that is still bothering me is the duplicate end/close events warning message.

So all pull request (for future visitors and to link everything):
https://github.com/aheckmann/gridfs-stream/pull/61
https://github.com/vsivsi/gridfs-locking-stream/pull/2

Thank you and let me know if you find any problems.

Regards,
Riaan

**Comment by vsivsi** [comment]
Hi @riaan53, this is great news and thanks for doing all of this work, I think it will be a big step forward. I'll take a look at this in detail tomorrow and try to get it merged and published ASAP.

**Comment by vsivsi** [comment]
Hi @riaan53, sorry to disappear for a few days, I've been dealing with a family emergency. I started to get all of this in-place last week, but I've run into some reliability problems with my gridfs-locks package when using the mongodb 2.0.15 driver. I haven't been able to isolate if the problem is with my code or some issue in the driver itself.  I'm going to try to keep making some progress on this over the coming days, but this family stuff may keep pulling me away. I'll do my best, thanks for your patience.

**Comment by riaan53** [comment]
Hi. No problem at all!

What reliability problems are you seeing? Do you think its with the new
changes in gridfs-stream? We have updated the writestream in gridfs-stream
with some enhancements but the PR is not in yet. The major change is that
no buffering will take place (node streams handles the buffering) - it just
delays the first write until the store is open and the 'finish' event will
be emitted when the store closes to indicate that the file is flushed and
committed. Then the normal 'close' event with file info as always.

Let me know if you find the problem and if there is anything I can help
with.

Regards,
Riaan

On Wednesday, February 18, 2015, Vaughn Iverson <notifications@github.com>
wrote:

> Hi @riaan53 <https://github.com/riaan53>, sorry to disappear for a few
> days, I've been dealing with a family emergency. I started to get all of
> this in-place last week, but I've run into some reliability problems with
> my gridfs-locks package when using the mongodb 2.0.15 driver. I haven't
> been able to isolate if the problem is with my code or some issue in the
> driver itself. I'm going to try to keep making some progress on this over
> the coming days, but this family stuff may keep pulling me away. I'll do my
> best, thanks for your patience.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vsivsi/meteor-file-collection/pull/27#issuecomment-74938616>
> .
>


-- 
Riaan Jacobs
riaan53@gmail.com

**Comment by vsivsi** [comment]
Hi, just a quick update... I've made some progress on this, but I'm still having issues with the combination of the new node mongo 2.0.x driver and the old mongodb server version 2.4.x.  Unfortunately, meteor still uses mongodb 2.4, so this case can't be ignored.  I'm going to work on it this afternoon. Hopefully the solution is straightforward, but I honestly don't know how much work has gone into ensuring that the new driver plays well with the older server.

**Comment by vsivsi** [comment]
Okay, I figured out what was happening and why.  The mongodb v2.0 driver documentation is still pretty rough, and I misinterpreted some API changes between 1.3 and 2.0. Specifically, `findOne()` still returns a plain old document, not a "new style" return value.  I'm not sure if that's a bug in the 2.0 driver or just poor/confusing documentation, but I've fixed it so it will work correctly in any case now.  With this, I can move on to looking at the gridfs-locking-stream package, which I should be able to do tonight or tomorrow.

**Comment by riaan53** [comment]
Ok cool! Thank you for this :) I hope all this work will pay off by further enhance this awesome package. 

I see that meteor is also upgrading the mongo driver to support up to mongodb v3 when it comes out and they will update mongodb to v2.6 for the meteor run command. https://github.com/meteor/meteor/blob/devel/History.md

Let me know if I can help with something and thanks for keeping me updated.

Regards,
Riaan

**Comment by vsivsi** [comment]
Okay, gridfs-locking-stream has been updated to version 1.0.0 with the latest of everything.  Tonight I'll work on merging these changes and finally release file-collection v1.0!  Woohoo!

**Comment by vsivsi** [comment]
Hi, Okay, I've merged everything together and it is passing the unit tests.  It's currently sitting on the `master` branch, pretty much read to go.  I want to do some more testing and documentation tonight, but it should be ready to publish tomorrow.

**Comment by riaan53** [comment]
Awesome! Thank you!!! :)

I have done a quick test and im seeing something strange with the flow control of the readstream, will investigate tonight and let you know. 

Also I see that I have made a mistake on https://github.com/vsivsi/meteor-file-collection/blob/master/gridFS_server.coffee#L225 . The following must be moved after the `if file` check.

```
         # Init the start and end range, default to full file
         range =
           start: 0
           end: file.length - 1

         # Check if this is a range request
         range = options.range if options.range?
```

**Comment by riaan53** [comment]
Hi @vsivsi ,

I have sort off found the cause of the readstream not being able to flow correctly. When writing data to the http get response writestream it returns `undefined` as in http://nodejs.org/api/stream.html#stream_writable_write_chunk_encoding_callback on https://github.com/vsivsi/meteor-file-collection/blob/master/http_access_server.coffee#L161

If you change the pipe to a write, pause on saturated, resume on drain implementation like below you can see the problem. `ready` is `undefined` so when using `pipe` it does not know that the writestream is saturated. I can provide a monkey patch to work around this issue for now but would like to find the cause of this.

```
      # Stream file
      if stream
         res.writeHead statusCode, headers
         #stream.pipe(res)
         stream.on 'data', (data) ->
            ready = res.write data
            console.log ready 
            if ready == false
               console.log 'pause'
               @pause()
               res.once 'drain', @resume.bind(this)  
```

I haven't figured out the problem yet, have reverted express and done some other check but no luck yet.

One more issue is that im getting this sometimes when uploading:

```
 MongoError: E11000 duplicate key error index: meteor.media.locks.$files_id_1  dup key: { : null }
```

Regards,
Riaan

**Comment by riaan53** [comment]
I have tested the above in my application but if I do the same with your file-collection test app the readstream works perfectly. Same meteor version as well. Heres the output:

```
I20150228-22:58:35.667(2)? false
I20150228-22:58:54.637(2)? pause
I20150228-22:58:57.307(2)? false
I20150228-22:58:57.307(2)? pause
I20150228-22:58:59.350(2)? true
```

I hope its not iron-router interfering.

So I think you can go ahead with the new release if you are happy. I will do a small PR for the `if file` check.

**Comment by vsivsi** [comment]
@riaan53   I'm still working on fixing some bugs revealed by my testing.  The worst one is a bug that causes resumable uploads creating more than 1000 chunks to fail.  It stems from a change in behavior in the mongodb 2.0.x node driver that by default limits the number of results from a `cursor.toArray()` call to 1000 documents.

Unfortunately, in trying to fix/work around this issue, I have uncovered an even more critical bug in the 2.0.x driver that I have reported here: https://jira.mongodb.org/browse/NODE-379
And fixed here: https://github.com/mongodb/node-mongodb-native/pull/1262

Not sure how long it will take for @christkv to turn this around on npm, but I obviously can't publish the new version of this package until this bug is fixed, since all gridFS collections have dots in their names.

**Comment by riaan53** [comment]
Hi @vsiverson ,

Thank you for the update! How do you veel overall about the new mongodb driver/gridfs-stream? 

Regards,
Riaan

**Comment by vsivsi** [comment]
Hi, things are working pretty well now. I had a bunch of problems with the mongodb 2.0.x driver. It's not completely stable yet, which is a bit concerning, but I think I've worked through the issues I was having with it.

I just completed some new functionality to resolve another issue: https://github.com/vsivsi/meteor-file-collection/issues/31

Now, the last thing I need to look at is how to restore the "file append" functionality that used to work with `upsertStream` and HTTP PUT requests.  This may not be practical in light of the changes in the mongodb/gridFS driver, but I'd at least like to give it a shot.

**Comment by vsivsi** [comment]
I've decided to just let the `upsertStream()` append functionality drop.  That's a semver breaking change, so file-collection will go to v1.0.0.  I plan to publish to atmosphere shortly.

**Comment by vsivsi** [comment]
vsivsi:file-collection@1.0.0 just published to Atmosphere!

**Comment by riaan53** [comment]
This is great news! Thank you for all the excellent work/help! Promise my next PR will be a bit easier :) 

Its a bit concerning about the new mongo driver instabilities.. Did you raise defects for them? 

Onto my next PR :) Would you be interested in adding Cordova support to file-collection? The changes to file-collection should be minimal - just the correct CORS handling. So to upload using HTTP multi-part POST just add the cordova-plugin-file-transfer, set the header for auth and then you are ready to go with file-collection. This is my thinking for the initial changes - just let file-collection accept the meteor cordova CORS requests. (No resumable.js support yet, but will add the CORS so long)

Then after that I want resumable/fault correction uploads from mobile :) I initially just modified resumable.js to work with the cordova file API (which is essentially the HTML5 File API) you just need to do a Filereader on the `blob` and then create a `blob` with data before sending it with xhr. It works but because this is done in javascript the mobile CPU tops 95-100% which is not good. So I will create my own cordova plugin (iOS and Android for now) to handle that part of resumble.js native on the mobile device. This is only for later on - for now just the CORS changes to file-collection to handle uploads using normal multi-part POST.

Let me know what you think and if this is something that want in file-colleciton.

Regards,
Riaan

**Comment by vsivsi** [comment]
CORS handling is a good idea, and seems like it would be pretty straightforward. I haven't worked with CORS a lot (just a bit of fiddling with CouchDB before settling on Meteor/MongoDB) and haven't written any Cordova apps, but go to town. As I mentioned on another thread, I've granted you collaborator rights on the project, so you won't need to fork and create PRs to develop these features. -V

**Comment by riaan53** [comment]
Awesome!! Thank you :)

**Pull request merged**
